[tool.poetry]
name = "practice"
version = "0.1.0"
description = ""
authors = ["Steed GL <steed@webglsoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8.0"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
